### ISSUE TITLE
Site Logo 

### ISSUE THREAD

**Issue by rishabh1403** [pollyfat/pollyfat.github.io#1]
Hi, I saw you are using cactus-dark theme, and were able to change logo from cactus to the bird, I had a doubt on how did you manage to change to color of bird on hover like the cactus plant.

**Comment by pollyfat** [comment]
1. Replace the images in YOUR-BLOG/themes/cactus-dark/source/images with your logo. You could generate your logo images with [http://realfavicongenerator.net](http://realfavicongenerator.net)
2. Edit YOUR-BLOG/themes/cactus-dark/_config.yml, change the url to your logo file name. Like ` url: /images/logo.png `

**Comment by rishabh1403** [comment]
Thank you,works like a charm :). I tried reading your articles, but language issues, what do you generally write about or are more inclined to ?

**Comment by pollyfat** [comment]
Just some notes.
